"""Remove uniqueness from config_name, config_type, and value

Revision ID: 195dfe92fbd2
Revises: 6f371aecb606
Create Date: 2025-01-19 16:31:05.135814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195dfe92fbd2'
down_revision = '6f371aecb606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_configuration_config_type')
        batch_op.create_index(batch_op.f('ix_configuration_config_type'), ['config_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_config_type'))
        batch_op.create_index('ix_configuration_config_type', ['config_type'], unique=1)

    # ### end Alembic commands ###
