"""empty message

Revision ID: 3f915a6f832c
Revises: 97918e9e5a4f
Create Date: 2025-01-19 16:44:25.529415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f915a6f832c'
down_revision = '97918e9e5a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_config_name'), ['config_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_config_name'))

    # ### end Alembic commands ###
