"""empty message

Revision ID: 64c292825362
Revises: 
Create Date: 2024-12-16 22:40:18.001472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c292825362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automatic_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_details', sa.String(length=64), nullable=False),
    sa.Column('script_location', sa.String(length=64), nullable=False),
    sa.Column('response_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automatic_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automatic_response_action_details'), ['action_details'], unique=False)
        batch_op.create_index(batch_op.f('ix_automatic_response_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_automatic_response_response_timestamp'), ['response_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_automatic_response_script_location'), ['script_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_automatic_response_status'), ['status'], unique=True)

    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=64), nullable=False),
    sa.Column('config_type', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_config_name'), ['config_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_configuration_config_type'), ['config_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_configuration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_value'), ['value'], unique=False)

    op.create_table('correlation_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('rule_query', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlation_rule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_rule_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_rule_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_rule_rule_query'), ['rule_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlation_rule_updated_at'), ['updated_at'], unique=False)

    op.create_table('retention_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_q', sa.String(length=256), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_rule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_rule_event_q'), ['event_q'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_rule_retention_period'), ['retention_period'], unique=True)
        batch_op.create_index(batch_op.f('ix_retention_rule_updated_at'), ['updated_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('connection_method', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_connection_method'), ['connection_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_event', sa.String(length=256), nullable=False),
    sa.Column('retention_period', sa.Integer(), nullable=False),
    sa.Column('p_datetime_timestamp', sa.DateTime(), nullable=False),
    sa.Column('p_data', sa.String(), nullable=False),
    sa.Column('retention_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['retention_rule_id'], ['retention_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_p_datetime_timestamp'), ['p_datetime_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_retention_period'), ['retention_period'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_retention_rule_id'), ['retention_rule_id'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlation_rule.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_incident_timestamp'), ['incident_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_status'))
        batch_op.drop_index(batch_op.f('ix_incident_notes'))
        batch_op.drop_index(batch_op.f('ix_incident_incident_timestamp'))
        batch_op.drop_index(batch_op.f('ix_incident_event_id'))
        batch_op.drop_index(batch_op.f('ix_incident_description'))
        batch_op.drop_index(batch_op.f('ix_incident_correlation_id'))

    op.drop_table('incident')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_retention_rule_id'))
        batch_op.drop_index(batch_op.f('ix_event_retention_period'))
        batch_op.drop_index(batch_op.f('ix_event_p_datetime_timestamp'))

    op.drop_table('event')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_connection_method'))

    op.drop_table('user')
    with op.batch_alter_table('retention_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_rule_updated_at'))
        batch_op.drop_index(batch_op.f('ix_retention_rule_retention_period'))
        batch_op.drop_index(batch_op.f('ix_retention_rule_event_q'))
        batch_op.drop_index(batch_op.f('ix_retention_rule_created_at'))

    op.drop_table('retention_rule')
    with op.batch_alter_table('correlation_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlation_rule_updated_at'))
        batch_op.drop_index(batch_op.f('ix_correlation_rule_rule_query'))
        batch_op.drop_index(batch_op.f('ix_correlation_rule_name'))
        batch_op.drop_index(batch_op.f('ix_correlation_rule_description'))
        batch_op.drop_index(batch_op.f('ix_correlation_rule_created_at'))

    op.drop_table('correlation_rule')
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_value'))
        batch_op.drop_index(batch_op.f('ix_configuration_updated_at'))
        batch_op.drop_index(batch_op.f('ix_configuration_created_at'))
        batch_op.drop_index(batch_op.f('ix_configuration_config_type'))
        batch_op.drop_index(batch_op.f('ix_configuration_config_name'))

    op.drop_table('configuration')
    with op.batch_alter_table('automatic_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automatic_response_status'))
        batch_op.drop_index(batch_op.f('ix_automatic_response_script_location'))
        batch_op.drop_index(batch_op.f('ix_automatic_response_response_timestamp'))
        batch_op.drop_index(batch_op.f('ix_automatic_response_action_type'))
        batch_op.drop_index(batch_op.f('ix_automatic_response_action_details'))

    op.drop_table('automatic_response')
    # ### end Alembic commands ###
