"""Remove uniqueness from config_name, config_type, and value

Revision ID: 97918e9e5a4f
Revises: 195dfe92fbd2
Create Date: 2025-01-19 16:31:44.642884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97918e9e5a4f'
down_revision = '195dfe92fbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_configuration_config_name')
        batch_op.create_index(batch_op.f('ix_configuration_config_name'), ['config_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_config_name'))
        batch_op.create_index('ix_configuration_config_name', ['config_name'], unique=1)

    # ### end Alembic commands ###
